version: '3'

services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_DATABASE: test
      MYSQL_PASSWORD: 12345
      MYSQL_ROOT_PASSWORD: 12345

  app:
    container_name: app
    image: app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSOWRD: 12345
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver

    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - mysqldb