#### GET request with a header
#GET http://localhost:8080/api/v1/clients
#Accept: application/json
#
#### Send POST request with json body
#POST http://localhost:8080/api/v1/clients
#Content-Type: application/json
#
#{
#  "lastName": "Nazarbekov",
#  "firstName": "Rashid",
#  "phoneNumber": "0709621762",
#  "notes": "jdhjkhfkfghfdshgkjl"
#}
#
#### GET request with a header
#GET http://localhost:8080/api/v1/clients/1
#Accept: application/json
#
####
#PUT http://localhost:8080/api/v1/clients/1
#Content-Type: application/json
#
#{
#  "lastName": "Nazarbekov",
#  "firstName": "Baiel",
#  "phoneNumber": "0709621762",
#  "notes": "jdhjkhfkfghfdshgkjl"
#}
#
####
#DELETE http://localhost:8080/api/v1/clients/1
#Accept: application/json
#
#### GET request with a header
#GET http://localhost:8080/api/v1/clients
#Accept: application/json

#-----------------------------------------------------------

### GET request with a header
GET http://localhost:8080/api/v1/staff
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/api/v1/staff
Content-Type: application/json

{
  "lastName": "Nazarbekov",
  "firstName": "Rashid",
  "position": "Manager",
  "phoneNumber": "0709621762"
}

### GET request with a header
GET http://localhost:8080/api/v1/staff/1
Accept: application/json

###
PUT http://localhost:8080/api/v1/staff/1
Content-Type: application/json

{
  "lastName": "Wick",
  "firstName": "John",
  "position": "Killer",
  "phoneNumber": "6546356466"
}

###
DELETE http://localhost:8080/api/v1/staff/1
Accept: application/json

### GET request with a header
GET http://localhost:8080/api/v1/staff
Accept: application/json
